# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'MissPokerGame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MissPokerGame
  pod 'Masonry'
  pod 'YYKit'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
      #关闭 Enable Modules
      config.build_settings['CLANG_ENABLE_MODULES'] = 'NO'
      # Xcode 14之后 pod库签名
      config.build_settings['CODE_SIGN_IDENTITY'] = ''
    end
  end
end
